name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: g++ main.c /braille/braille.c -o braille
    - name: check
      run: ./braille
    - name: date
      run: date
