name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install mingw
      run: sudo apt-get install mingw-w64
    - uses: actions/checkout@v1
    - name: make
      run: |
        gcc main.c braille/braille.c -o out
#        i686-w64-mingw32-gcc -o braille.exe main.c braille/braille.c

    - name: check
      run: ./out
    - run: mkdir -p output
      
#    - run: cp *.exe output
      
    - run: |
        sudo apt-get install mailutils
        echo "Message Body Here" | mailx -s "CI email Test" gouravkalye@gmail.com
      
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: output
    - name: date
      run: date
