name: ESP8266 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependancies
      run: |
        sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python python-serial
      
      
    - name: download sdk
      run: |
        mkdir -p ~/esp
        cd ~/esp
        tar -xzf ~/Downloads/xtensa-lx106-elf-linux64-1.22.0-100-ge567ec7-5.2.0.tar.gz
      
    - name: export path
      run: |
        export PATH="$PATH:$HOME/esp/xtensa-lx106-elf/bin"
        printenv PATH
