name: ESP8266 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
      steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        sudo apt-get install git make python python-pip
        mkdir -p $HOME/esp8266
      
      
    - name: download sdk
      run: |
        cd $HOME/esp8266
        git clone --recursive git@github.com:pfalcon/esp-open-sdk.git
        cd esp-open-sdk
        make STANDALONE=y
      
    - name: date
      run: date
